[deps]
H5Zblosc = "c8ec2601-a99c-407f-b158-e79c03c2f5f7"
H5Zlz4 = "eb20ec05-5464-47b5-ba41-098e3c1068a3"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
JLD2 = "033835bb-8acc-5ee8-8aae-3f567f8a3819"
JLD2Bitshuffle = "339bd13f-8489-4f40-8c7d-2f9e70a62d43"
JLD2Blosc = "7f28b69e-c83f-4960-977f-81f66861f7ce"
JLD2Bzip2 = "84687f94-9f67-4744-9d95-d64e07ea2a3b"
JLD2Lz4 = "49ca2578-dfa4-4b24-b5ab-b610893dc52a"
JLD2Zstd = "8968170a-ce43-4a8a-abc0-107004fa2de1"
